### ISSUE TITLE
Can't seem to get this working in RLcraft 1.12.2 server 

### ISSUE THREAD

**Issue by itsdukey** [LionZXY/AromaBackupS3#2]
Hello, i know this project is old but it's exactly what i need to backup a server i play with a friend

So far i install everything with auroma backup, and 1997core. everything runs fine.

Would really appreciate the help if you could provide it! lost 4 hours of grinding earlier and this may just save my sanity

When i add your S3 addon the server just keeps erroring out stating: 

Link to crash report log
https://mclo.gs/Qad0xcd

Red part!
"<html>
<body>

[21:26:03] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
--
4147 | java.lang.NoClassDefFoundError: aroma1997/backup/common/notification/IBackupNotification
4148 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_362]
4149 | at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_362]
4150 | at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539) ~[forge.jar:?]
4151 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
4152 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
4153 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
4154 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
4155 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
4156 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
4157 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
4158 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
4159 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
4160 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
4161 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
4162 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[LoadController.class:?]
4163 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[LoadController.class:?]
4164 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
4165 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
4166 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
4167 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
4168 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
4169 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
4170 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
4171 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
4172 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
4173 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
4174 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
4175 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
4176 | at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595) ~[Loader.class:?]
4177 | at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
4178 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
4179 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
4180 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
4181 | at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
4182 | Caused by: java.lang.ClassNotFoundException: aroma1997.backup.common.notification.IBackupNotification
4183 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
4184 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_362]
4185 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_362]
4186 | ... 34 more
4187 | Caused by: java.lang.NullPointerException
4188 | [21:26:03] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /server/./crash-reports/crash-2023-03-04_21.26.03-server.txt

<html>
<body>

[21:26:03] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
--
4147 | java.lang.NoClassDefFoundError: aroma1997/backup/common/notification/IBackupNotification
4148 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_362]
4149 | at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_362]
4150 | at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539) ~[forge.jar:?]
4151 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
4152 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
4153 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
4154 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
4155 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
4156 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
4157 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
4158 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
4159 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
4160 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
4161 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
4162 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[LoadController.class:?]
4163 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[LoadController.class:?]
4164 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
4165 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
4166 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
4167 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
4168 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
4169 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
4170 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
4171 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
4172 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
4173 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
4174 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
4175 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
4176 | at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595) ~[Loader.class:?]
4177 | at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
4178 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
4179 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
4180 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
4181 | at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
4182 | Caused by: java.lang.ClassNotFoundException: aroma1997.backup.common.notification.IBackupNotification
4183 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
4184 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_362]
4185 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_362]
4186 | ... 34 more
4187 | Caused by: java.lang.NullPointerException
4188 | [21:26:03] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /server/./crash-reports/crash-2023-03-04_21.26.03-server.txt

</body>
</html>
